### ISSUE TITLE
Additional EDA metadata needed

### ISSUE THREAD

**Issue by alisonlhart** [kentik/ansible_eda#3]
To display EDA content on Ansible Automation Hub, there is an additional file needed in the collection.

Add the `meta/extensions.yml` file to the collection with the following contents:
```
extensions:
  - args:
      ext_dir: eda/plugins/event_filter
  - args:
      ext_dir: eda/plugins/event_source
```
This will cause the EDA plugin to display under the ["Contents"](https://console.redhat.com/ansible/automation-hub/repo/published/kentik/ansible_eda/content/) tab in Automation Hub.

See the [ansible.eda collection source](https://github.com/ansible/event-driven-ansible/blob/main/meta/extensions.yml) for reference.
